# Generated by Django 6.0.3 on 2026-03-31 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_availability_day'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appintments',
            constraint=models.UniqueConstraint(fields=('date', 'start_time'), name='date_time'),
        ),
    ]
