# Generated by Django 6.0.3 on 2026-04-02 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appintments_date_time'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='Pending', max_length=30)),
                ('mes_result', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='appintments',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='appintments',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appintments',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='appointments',
            constraint=models.UniqueConstraint(fields=('date', 'start_time'), name='date_time'),
        ),
        migrations.DeleteModel(
            name='Appintments',
        ),
    ]
