# Generated by Django 6.0.3 on 2026-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointments_remove_appintments_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
